#!/bin/sh
set -eu
lb config noauto \
    --mode debian \
    --system live \
    --distribution trixie \
    --debian-installer live \
    --debian-installer-distribution trixie \
    --debian-installer-gui false \
    --architecture amd64 \
    --archive-areas "main contrib non-free-firmware" \
    --binary-images iso-hybrid \
    --bootloaders "syslinux grub-efi" \
    --linux-packages none \
    --firmware-binary true \
    --firmware-chroot true \
    --apt-recommends false \
    --debootstrap-options "--variant=minbase --include=ca-certificates" \
    --memtest none \
    --bootappend-live "boot=live components console=tty0 console=ttyS0,115200n8" \
    --iso-application "Znlite Linux" \
    --iso-publisher "Znlite Linux project" \
    --iso-volume "ZNLITE_TEXT" \
    "${@}"
